# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each time that oh-my-zsh is loaded.
# gozilla
# af-magic
# kolo
# bira
# wedisagree
# mgutz
# kennethreitz
# lambda
# imajes
# crcandy
# frisk, works in ubuntu
# dstufft

ZSH_THEME="theunraveler"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"
DISABLE_AUTO_UPDATE="true"
DISABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git bundler brew gem knife history history-substring-search node npm bower vagrant themes berks extract)

# amend the path, for more http://daniel.hepper.net/blog/2011/02/change-order-of-path-entries-on-mac-os-x/
# edit /etc/paths file manually, or amend path here
export PATH="/usr/local/bin:/usr/local/sbin:$PATH"

# export EDITOR='vim'
export EDITOR='sb -w'

source $ZSH/oh-my-zsh.sh

[[ -f $HOME/.zsh_aliases ]] && source $HOME/.zsh_aliases

[[ -f $HOME/.ssh_aliases ]] && source $HOME/.ssh_aliases

# PATH for rbenv, it seems now brew-installed rbenv have this path,see env | grep PATH
# export PATH="$HOME/.rbenv/shims:$PATH"
# add support for Homebrew installed rbenv
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# add npm support
export PATH="/usr/local/share/npm/bin:$PATH"

# add completion for aws cli
source /usr/local/bin/aws_zsh_completer.sh
export AWS_CONFIG_FILE="~/.AWS_Config"

# add support for homebrew installed autojump
[[ -s `brew --prefix`/etc/autojump.sh ]] && . `brew --prefix`/etc/autojump.sh

[[ -s $HOME/.tmuxinator/scripts/tmuxinator ]] && source $HOME/.tmuxinator/scripts/tmuxinator

# set PS1 in macvim, http://stackoverflow.com/questions/12942781/zsh-correct-shell-input-output-inside-vim-macvim
if [[ $TERM == 'dumb' ]]; then
  export RPS1="\n\w\n\u $ "
fi

# this loads NVM
[[ -s /Users/dfang/.nvm/nvm.sh ]] && . /Users/dfang/.nvm/nvm.sh

# this loads fasd
eval "$(fasd --init auto)"
